<?php

namespace Mooncascade\Listeners;

use Mooncascade\Events\MooncascadeEventCompletedEvent;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Mooncascade\Events\MoonscadeBaseEventInterface;
use Mooncascade\Managers\MooncascadeFCMManager;

class MooncascadeEventCompletedEventListener extends AbstractFCMEventListener
{
    protected $key = 'event-completed';

    /**
     * AbstractFCMEventListener constructor.
     * @param MooncascadeFCMManager $mooncascadeFCMManager
     */
    public function __construct(MooncascadeFCMManager $mooncascadeFCMManager)
    {
        parent::__construct($mooncascadeFCMManager);
    }

    /**
     * @param MoonscadeBaseEventInterface $event
     */
    public function handle(MoonscadeBaseEventInterface $event)
    {
        echo 'Should TOTES be called now';

        parent::handle($event); // TODO: Change the autogenerated stub
    }


}
