<?php

namespace Mooncascade\Listeners;

use Mooncascade\Events\MooncascadeDelayedStartEvent;
use Mooncascade\Events\MoonscadeBaseEventInterface;

class MooncascadeDelayedStartEventListener extends AbstractFCMEventListener
{

    /**
     * @var string
     */
    protected $key = 'event';

    /**
     * @param MoonscadeBaseEventInterface $event
     */
    public function handle(MoonscadeBaseEventInterface $event)
    {
        parent::handle($event); // TODO: Change the autogenerated stub
    }
}
